name: DEPLOY
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build --if-present
        - name: Running npm tests
          run: npm test -- --watch=false --progress=false
          env:
            CI: true
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -r -e "ssh ${{ secrets.USERNAME }}@ligone.imag.fr ssh"
          path: dist/prod/.
          remote_path: /var/www/html/stable
          remote_host: lig-augcom.imag.fr
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
